/** @jest-environment node */
/**
 * scripts/templates/build-thumb-blur.mjs — template thumbnails → lib/studio/templateThumbs.generated.ts (`v` = the file's
 * hash, `blur` = a ≤ 16 px WebP). Run against a fixture root in a temp dir; the real module is only READ.
 */
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, unlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import sharp from 'sharp';
import { buildBlurMap, collectThumbPaths, parseBlurArgs, parseBlurModule } from './build-thumb-blur.mjs';

const ROOT = process.cwd();
const SCRIPT = join(ROOT, 'scripts/templates/build-thumb-blur.mjs');

type Entry = { v: string; blur: string };
type Result = { entries: Record<string, Entry>; added: string[]; changed: string[]; removed: string[]; missing: string[]; refused: string[]; failed: unknown[]; current: boolean; wrote: boolean };

let dir: string;
beforeEach(() => { dir = mkdtempSync(join(tmpdir(), 'thumb-blur-')); });
afterEach(() => rmSync(dir, { recursive: true, force: true }));

const picture = async (rel: string, width: number, height: number, rgb: [number, number, number], format: 'jpeg' | 'png' = 'jpeg') => {
  const file = join(dir, 'public', rel);
  mkdirSync(dirname(file), { recursive: true });
  const img = sharp({ create: { width, height, channels: 3, background: { r: rgb[0], g: rgb[1], b: rgb[2] } } });
  writeFileSync(file, await (format === 'png' ? img.png() : img.jpeg()).toBuffer());
};
const cards = (...thumbs: string[]) => {
  mkdirSync(join(dir, 'lib/studio'), { recursive: true });
  writeFileSync(join(dir, 'lib/studio/templates.ts'), thumbs.map((t, i) => `  { tool: 'video', id: 'c${i}',\n    thumb: ${t}, palette: ['#000000', '#FFFFFF'] },`).join('\n'));
};
const opts = () => parseBlurArgs(['--root', dir]) as ReturnType<typeof parseBlurArgs>;
const build = async (check = false) => (await buildBlurMap({ ...opts(), check }, sharp)) as Result;
const moduleText = () => readFileSync(join(dir, 'lib/studio/templateThumbs.generated.ts'), 'utf8');
const sha10 = (rel: string) => createHash('sha256').update(readFileSync(join(dir, 'public', rel))).digest('hex').slice(0, 10);

test('cards + public/templates → one sorted entry per picture: its hash, and a real ≤ 16 px WebP in its proportions', async () => {
  await picture('templates/video/reel.jpg', 600, 800, [20, 60, 120]);
  await picture('avatars/face.jpg', 1024, 1024, [200, 150, 120]);
  cards("'/templates/video/reel.jpg'", "'/avatars/face.jpg'", 'null');
  const r = await build();
  expect(r.wrote).toBe(true);
  expect(r.added).toEqual(['/avatars/face.jpg', '/templates/video/reel.jpg']);
  const text = moduleText();
  expect(text).toMatch(/^\/\/ GENERATED by scripts\/templates\/build-thumb-blur\.mjs/);
  expect(text).toContain('export const TEMPLATE_THUMB_META');
  const parsed = parseBlurModule(text) as Record<string, Entry>;
  expect(Object.keys(parsed)).toEqual(['/avatars/face.jpg', '/templates/video/reel.jpg']);
  for (const [p, [w, h]] of [['/templates/video/reel.jpg', [12, 16]], ['/avatars/face.jpg', [16, 16]]] as const) {
    expect(parsed[p]!.v).toBe(sha10(p.slice(1)));
    const tiny = await sharp(Buffer.from(parsed[p]!.blur.replace('data:image/webp;base64,', ''), 'base64')).metadata();
    expect({ p, format: tiny.format, w: tiny.width, h: tiny.height }).toEqual({ p, format: 'webp', w, h });
  }
});

test('deterministic and re-runnable: a second run changes nothing and does not touch the file', async () => {
  await picture('templates/image/product.jpg', 600, 800, [90, 40, 10]);
  cards("'/templates/image/product.jpg'");
  await build();
  const first = moduleText();
  const mtime = statSync(join(dir, 'lib/studio/templateThumbs.generated.ts')).mtimeMs;
  const again = await build();
  expect(again).toMatchObject({ current: true, wrote: false, added: [], changed: [], removed: [] });
  expect(moduleText()).toBe(first);
  expect(statSync(join(dir, 'lib/studio/templateThumbs.generated.ts')).mtimeMs).toBe(mtime);
});

test('a re-run picks up a NEW picture on its own (even before a card points at it), a replaced one, and a removed one', async () => {
  await picture('templates/video/reel.jpg', 600, 800, [20, 60, 120]);
  await picture('templates/video/trailer.jpg', 600, 800, [120, 90, 20]);
  cards("'/templates/video/reel.jpg'", "'/templates/video/trailer.jpg'");
  await build();
  const oldReel = (parseBlurModule(moduleText()) as Record<string, Entry>)['/templates/video/reel.jpg']!.v;

  await picture('templates/music/jazz.png', 880, 1168, [10, 10, 40], 'png'); // build-thumbs.mjs just wrote it; no thumb: line yet
  await picture('templates/video/reel.jpg', 600, 800, [240, 10, 10]); // a better take, same name
  unlinkSync(join(dir, 'public/templates/video/trailer.jpg'));
  cards("'/templates/video/reel.jpg'");
  const r = await build();
  expect({ added: r.added, changed: r.changed, removed: r.removed }).toEqual({
    added: ['/templates/music/jazz.png'], changed: ['/templates/video/reel.jpg'], removed: ['/templates/video/trailer.jpg'],
  });
  const now = parseBlurModule(moduleText()) as Record<string, Entry>;
  expect(now['/templates/video/reel.jpg']!.v).not.toBe(oldReel); // a new URL — the immutable cache cannot serve the old take
  expect(now['/templates/video/reel.jpg']!.v).toBe(sha10('templates/video/reel.jpg'));
});

test('a card pointing at a missing file is reported (not invented); a path that climbs out of public/ is refused, never read', () => {
  cards("'/avatars/gone.jpg'", "'/templates/../../etc/passwd.jpg'", "'https://cdn.example.org/a.jpg'");
  const source = readFileSync(join(dir, 'lib/studio/templates.ts'), 'utf8');
  expect(collectThumbPaths({ publicDir: join(dir, 'public'), templatesSource: source })).toEqual({
    paths: [], missing: ['/avatars/gone.jpg'], refused: ['/templates/../../etc/passwd.jpg'],
  });
});

test('the CLI: writes the map, `--check` passes when current and exits 2 (writing nothing) when a picture changed', async () => {
  await picture('templates/video/reel.jpg', 600, 800, [20, 60, 120]);
  cards("'/templates/video/reel.jpg'");
  const run = (...extra: string[]) => spawnSync(process.execPath, [SCRIPT, '--root', dir, ...extra], { cwd: ROOT, encoding: 'utf8', timeout: 60_000 });

  const write = run();
  expect({ status: write.status, stderr: write.stderr }).toMatchObject({ status: 0 });
  expect(write.stdout).toMatch(/blur map .*templateThumbs\.generated\.ts: 1 picture \(\+1 new · ~0 changed · -0 removed\)/);
  expect(run('--check').status).toBe(0);

  await picture('templates/video/reel.jpg', 600, 800, [250, 250, 0]);
  const before = moduleText();
  const stale = run('--check');
  expect(stale.status).toBe(2);
  expect(stale.stdout).toContain('stale — run: node scripts/templates/build-thumb-blur.mjs');
  expect(moduleText()).toBe(before);
});
