/**
 * Avatar G Commerce Module - Barrel Export
 * Single import point for all commerce utilities
 */

// Validation schemas ONLY (not the inferred types to avoid conflicts with types.ts)
export {
  CreateWalletSchema,
  DepositToWalletSchema,
  WithdrawFromWalletSchema,
  WalletTransactionSchema,
  CreateOrderSchema,
  UpdateOrderSchema,
  OrderSchema,
  CreateOrderItemSchema,
  CreateAffiliateSchema,
  AffiliateTrackingSchema,
  TrackAffiliateClickSchema,
  CreateAffiliateConversionSchema,
  CreateDigitalLicenseSchema,
  DigitalLicenseSchema,
  TransferDigitalLicenseSchema,
  CreateSupplierProductSchema,
  SearchSupplierProductsSchema,
  CreateShopStoreSchema,
  ShopStoreSchema,
  CreateProductSchema,
  UpdateProductSchema,
  ProductSchema,
  UserConsentSchema,
  RequestDataExportSchema,
  DeleteAccountSchema,
  ShippingProfileSchema,
  CreateShippingProfileSchema,
  ShippingEventSchema,
  AddShippingEventSchema,
  SelectShippingProfileSchema,
  ShippingTrackingSchema,
  ComputeMarginSchema,
  ValidateProductForPublishingSchema,
  BulkMarginCheckSchema,
  ComputeOrderSplitSchema,
  ComputeProductMarginSchema,
  // Inferred validation types (prefixed to avoid conflicts)
  type CreateWallet,
  type DepositToWallet,
  type WithdrawFromWallet,
  type CreateOrder,
  type UpdateOrder,
  type CreateOrderItem,
  type CreateAffiliate,
  type TrackAffiliateClick,
  type CreateAffiliateConversion,
  type CreateDigitalLicense,
  type TransferDigitalLicense,
  type CreateSupplierProduct,
  type SearchSupplierProducts,
  type CreateShopStore,
  type CreateProduct,
  type UpdateProduct,
  type RequestDataExport,
  type DeleteAccount,
  type CreateShippingProfile,
  type AddShippingEvent,
  type SelectShippingProfile,
  type ComputeMargin,
  type ValidateProductForPublishing,
  type BulkMarginCheck,
  type ComputeOrderSplit,
  type ComputeProductMargin,
} from './validation';

// Types (use these as primary types, not the inferred validation types)
export type {
  ShopWallet,
  WalletTransaction,
  OrderStatus,
  FulfillmentStatus,
  Order,
  OrderItem,
  OrderSplit,
  AffiliateTracking,
  AffiliateClick,
  AffiliateConversion,
  DigitalLicense,
  SupplierProduct,
  ShopStore,
  Product,
  UserConsent,
  ShippingProfile,
  ShippingEvent,
  ShippingTracking,
  ApiResponse,
  PaginatedResponse,
} from './types';

// Server utilities (use server actions)
export * from './server';
