import {
  Clapperboard,
  Code2,
  Gamepad2,
  Image,
  Music2,
  Sofa,
  UserCircle2,
  Wand2,
} from 'lucide-react';
import type { OmniServiceDescriptor, ServiceId } from './types';

export const OMNI_SERVICES: OmniServiceDescriptor[] = [
  {
    id: 'avatar',
    title: 'Avatar',
    subtitle: 'Identity and persona generation',
    short: 'AV',
    worker: 'AvatarComposer',
    accent: '#7cd4ff',
    previewKind: 'image',
    defaultPrompt: 'Create a premium avatar portrait with cinematic lighting and confident expression.',
    icon: UserCircle2,
  },
  {
    id: 'video',
    title: 'Video',
    subtitle: 'Storyboarding and scene generation',
    short: 'VD',
    worker: 'VideoGenWorker',
    accent: '#ff9f43',
    previewKind: 'video',
    defaultPrompt: 'Generate a 15-second cinematic launch video concept with scene-by-scene breakdown.',
    icon: Clapperboard,
  },
  {
    id: 'image',
    title: 'Image',
    subtitle: 'Visual concepts and still assets',
    short: 'IM',
    worker: 'ImageGenWorker',
    accent: '#ffbf5f',
    previewKind: 'image',
    defaultPrompt: 'Create a hero visual for AI product launch with premium modern aesthetic.',
    icon: Image,
  },
  {
    id: 'music',
    title: 'Music',
    subtitle: 'Soundtrack and mood generation',
    short: 'MU',
    worker: 'MusicLabWorker',
    accent: '#7bf0b0',
    previewKind: 'audio',
    defaultPrompt: 'Compose an atmospheric soundtrack suitable for a high-end product trailer.',
    icon: Music2,
  },
  {
    id: 'game-creation',
    title: 'Game Creation',
    subtitle: 'Gameplay ideas and interactive systems',
    short: 'GM',
    worker: 'GameCreationWorker',
    accent: '#b8f861',
    previewKind: 'text',
    defaultPrompt: 'Design a complete game concept with mechanics, progression, and monetization loop.',
    icon: Gamepad2,
  },
  {
    id: 'interior-design',
    title: 'Interior Design',
    subtitle: 'Space concepts and furnishing direction',
    short: 'IN',
    worker: 'InteriorDesignWorker',
    accent: '#f7d17f',
    previewKind: 'image',
    defaultPrompt: 'Generate a luxury interior concept with materials, lighting, and furniture layout.',
    icon: Sofa,
  },
  {
    id: 'prompt-builder',
    title: 'Prompt Builder',
    subtitle: 'Prompt templates and optimization',
    short: 'PR',
    worker: 'PromptBuilderWorker',
    accent: '#ffd166',
    previewKind: 'text',
    defaultPrompt: 'Build a structured high-conversion prompt template for multimodal generation tasks.',
    icon: Wand2,
  },
  {
    id: 'terminal-coding',
    title: 'Terminal & Coding',
    subtitle: 'Developer tools, scripts, and code execution',
    short: 'TC',
    worker: 'TerminalCodingWorker',
    accent: '#64d2ff',
    previewKind: 'text',
    defaultPrompt: 'Generate terminal commands and production-ready code implementation steps for the requested task.',
    icon: Code2,
  },
];

export const OMNI_SERVICE_MAP: Record<ServiceId, OmniServiceDescriptor> = OMNI_SERVICES.reduce(
  (acc, item) => {
    acc[item.id] = item;
    return acc;
  },
  {} as Record<ServiceId, OmniServiceDescriptor>,
);
