import {
  Bot,
  Building2,
  Crown,
  UserCircle2,
  Image,
  Clapperboard,
  Mic2,
  Music2,
  FileText,
  Workflow,
  LineChart,
  ShoppingCart,
  Truck,
} from 'lucide-react';
import type { OmniServiceDescriptor, ServiceId } from './types';

export const OMNI_SERVICES: OmniServiceDescriptor[] = [
  {
    id: 'agent-g',
    title: 'Agent G Core',
    subtitle: 'Primary orchestration brain',
    short: 'AG',
    worker: 'PrimaryAgent',
    accent: '#4de2ff',
    previewKind: 'text',
    defaultPrompt: 'Draft a complete campaign command plan with dependencies.',
    icon: Bot,
  },
  {
    id: 'business-strategy',
    title: 'Business Strategy',
    subtitle: 'Growth and monetization strategy',
    short: 'BS',
    worker: 'BusinessPlanner',
    accent: '#5cf2b5',
    previewKind: 'text',
    defaultPrompt: 'Map a quarterly growth blueprint from current assets.',
    icon: Building2,
  },
  {
    id: 'executive-ops',
    title: 'Executive Ops',
    subtitle: 'Decision board and executive briefs',
    short: 'EO',
    worker: 'ExecutiveAdvisor',
    accent: '#ff8fa3',
    previewKind: 'text',
    defaultPrompt: 'Summarize operational risk and executive actions for this week.',
    icon: Crown,
  },
  {
    id: 'avatar-studio',
    title: 'Avatar Studio',
    subtitle: 'Identity and persona generation',
    short: 'AV',
    worker: 'AvatarComposer',
    accent: '#9ba7ff',
    previewKind: 'image',
    defaultPrompt: 'Generate a premium executive avatar with cinematic lighting.',
    icon: UserCircle2,
  },
  {
    id: 'image-gen',
    title: 'Image Generator',
    subtitle: 'Campaign visuals and still assets',
    short: 'IM',
    worker: 'ImageGenWorker',
    accent: '#ffbf5f',
    previewKind: 'image',
    defaultPrompt: 'Create a hero image for an AI command center launch.',
    icon: Image,
  },
  {
    id: 'video-gen',
    title: 'Video Generator',
    subtitle: 'Motion concepts and scene planning',
    short: 'VD',
    worker: 'VideoGenWorker',
    accent: '#ff9f43',
    previewKind: 'video',
    defaultPrompt: 'Compose a thirty second cinematic teaser from latest visuals.',
    icon: Clapperboard,
  },
  {
    id: 'voice-synth',
    title: 'Voice Synth',
    subtitle: 'Voiceover and speech synthesis',
    short: 'VS',
    worker: 'VoiceSynthWorker',
    accent: '#7cf3ff',
    previewKind: 'audio',
    defaultPrompt: 'Generate a confident executive narration for launch video.',
    icon: Mic2,
  },
  {
    id: 'music-lab',
    title: 'Music Lab',
    subtitle: 'Mood bed and soundtrack generation',
    short: 'MU',
    worker: 'MusicLabWorker',
    accent: '#7bf0b0',
    previewKind: 'audio',
    defaultPrompt: 'Compose a luxury retro synth soundtrack with modern pulse.',
    icon: Music2,
  },
  {
    id: 'copy-engine',
    title: 'Copy Engine',
    subtitle: 'Narrative, ad copy, and scripts',
    short: 'CP',
    worker: 'CopyEngineWorker',
    accent: '#66d6ff',
    previewKind: 'text',
    defaultPrompt: 'Write high-conversion ad copy for enterprise AI launch.',
    icon: FileText,
  },
  {
    id: 'workflow-automation',
    title: 'Workflow Automation',
    subtitle: 'Cross-service pipeline control',
    short: 'WF',
    worker: 'WorkflowWorker',
    accent: '#b8f861',
    previewKind: 'workflow',
    defaultPrompt: 'Link image, voice, and video modules into a scheduled pipeline.',
    icon: Workflow,
  },
  {
    id: 'analytics-hub',
    title: 'Analytics Hub',
    subtitle: 'Telemetry and spend intelligence',
    short: 'AN',
    worker: 'AnalyticsWorker',
    accent: '#8ab8ff',
    previewKind: 'text',
    defaultPrompt: 'Analyze campaign efficiency and output a concise scorecard.',
    icon: LineChart,
  },
  {
    id: 'commerce-pilot',
    title: 'Commerce Pilot',
    subtitle: 'Offer design and storefront strategy',
    short: 'CM',
    worker: 'CommerceWorker',
    accent: '#9af4d7',
    previewKind: 'text',
    defaultPrompt: 'Build a conversion offer bundle from existing assets.',
    icon: ShoppingCart,
  },
  {
    id: 'fulfillment-hq',
    title: 'Fulfillment HQ',
    subtitle: 'Delivery tracking and operations',
    short: 'FH',
    worker: 'FulfillmentWorker',
    accent: '#f7d17f',
    previewKind: 'workflow',
    defaultPrompt: 'Prepare a handoff and fulfillment timeline for approved outputs.',
    icon: Truck,
  },
];

export const OMNI_SERVICE_MAP: Record<ServiceId, OmniServiceDescriptor> = OMNI_SERVICES.reduce(
  (acc, item) => {
    acc[item.id] = item;
    return acc;
  },
  {} as Record<ServiceId, OmniServiceDescriptor>,
);
