import {
  Calendar,
  Clapperboard,
  Code2,
  Gamepad2,
  Image,
  Mic2,
  Music2,
  PenLine,
  Radio,
  Sofa,
  UserCircle2,
  Wand2,
  Globe,
  Drama,
} from 'lucide-react';
import type { OmniServiceDescriptor, ServiceId } from './types';

export const OMNI_SERVICES: OmniServiceDescriptor[] = [
  {
    id: 'avatar',
    title: 'Avatar',
    subtitle: 'AI talking avatar via HeyGen',
    short: 'AV',
    worker: 'AvatarComposer',
    accent: '#7cd4ff',
    previewKind: 'video',
    defaultPrompt: 'Hello! I am your AI avatar from MyAvatar.ge. I am ready to represent you professionally.',
    icon: UserCircle2,
  },
  {
    id: 'video',
    title: 'Video',
    subtitle: 'Storyboarding and scene generation',
    short: 'VD',
    worker: 'VideoGenWorker',
    accent: '#ff9f43',
    previewKind: 'video',
    defaultPrompt: 'Generate a 15-second cinematic launch video concept with scene-by-scene breakdown.',
    icon: Clapperboard,
  },
  {
    id: 'image',
    title: 'Image',
    subtitle: 'Visual concepts and still assets',
    short: 'IM',
    worker: 'ImageGenWorker',
    accent: '#ffbf5f',
    previewKind: 'image',
    defaultPrompt: 'Create a hero visual for AI product launch with premium modern aesthetic.',
    icon: Image,
  },
  {
    id: 'music',
    title: 'Music',
    subtitle: 'Soundtrack and mood generation',
    short: 'MU',
    worker: 'MusicLabWorker',
    accent: '#7bf0b0',
    previewKind: 'audio',
    defaultPrompt: 'Compose an atmospheric soundtrack suitable for a high-end product trailer.',
    icon: Music2,
  },
  {
    id: 'game-creation',
    title: 'Game Creation',
    subtitle: 'Gameplay ideas and interactive systems',
    short: 'GM',
    worker: 'GameCreationWorker',
    accent: '#b8f861',
    previewKind: 'text',
    defaultPrompt: 'Design a complete game concept with mechanics, progression, and monetization loop.',
    icon: Gamepad2,
  },
  {
    id: 'interior-design',
    title: 'Interior Design',
    subtitle: 'Space concepts and furnishing direction',
    short: 'IN',
    worker: 'InteriorDesignWorker',
    accent: '#f7d17f',
    previewKind: 'image',
    defaultPrompt: 'Generate a luxury interior concept with materials, lighting, and furniture layout.',
    icon: Sofa,
  },
  {
    id: 'prompt-builder',
    title: 'Prompt Builder',
    subtitle: 'Prompt templates and optimization',
    short: 'PR',
    worker: 'PromptBuilderWorker',
    accent: '#ffd166',
    previewKind: 'text',
    defaultPrompt: 'Build a structured high-conversion prompt template for multimodal generation tasks.',
    icon: Wand2,
  },
  {
    id: 'terminal-coding',
    title: 'Terminal & Coding',
    subtitle: 'Developer tools, scripts, and code execution',
    short: 'TC',
    worker: 'TerminalCodingWorker',
    accent: '#64d2ff',
    previewKind: 'text',
    defaultPrompt: 'Generate terminal commands and production-ready code implementation steps for the requested task.',
    icon: Code2,
  },
  {
    id: 'content-writer',
    title: 'Content Writer',
    subtitle: 'Articles, posts and marketing copy',
    short: 'CW',
    worker: 'ContentWriterWorker',
    accent: '#c084fc',
    previewKind: 'text',
    defaultPrompt: 'Write a compelling long-form article about AI and the future of work in Georgia.',
    icon: PenLine,
  },
  {
    id: 'podcast',
    title: 'Podcast',
    subtitle: 'Scripts, episodes and audio content',
    short: 'PD',
    worker: 'PodcastWorker',
    accent: '#f472b6',
    previewKind: 'text',
    defaultPrompt: 'Write a 10-minute podcast episode script about technology trends in Georgia for 2026.',
    icon: Radio,
  },
  {
    id: 'character',
    title: 'Character',
    subtitle: 'AI character creation and backstory',
    short: 'CH',
    worker: 'CharacterWorker',
    accent: '#a78bfa',
    previewKind: 'text',
    defaultPrompt: 'Create a detailed AI character with name, backstory, personality traits and dialogue examples.',
    icon: Drama,
  },
  {
    id: 'event',
    title: 'Event Studio',
    subtitle: 'AI event content and full scenario',
    short: 'EV',
    worker: 'EventWorker',
    accent: '#34d399',
    previewKind: 'text',
    defaultPrompt: 'Create a complete event scenario with timeline, program, and promotional content.',
    icon: Calendar,
  },
  {
    id: 'tourism',
    title: 'Tourism & Travel',
    subtitle: 'Travel plans, local guides and itineraries',
    short: 'TR',
    worker: 'TourismWorker',
    accent: '#0ea5e9',
    previewKind: 'text',
    defaultPrompt: 'Create a 7-day Georgia travel itinerary with hidden gems, local food recommendations and cultural highlights.',
    icon: Globe,
  },
  {
    id: 'voice-studio',
    title: 'Voice Studio',
    subtitle: 'AI voice synthesis and TTS',
    short: 'VS',
    worker: 'VoiceStudioWorker',
    accent: '#fb923c',
    previewKind: 'audio',
    defaultPrompt: 'Generate a professional voice-over script for a 60-second product commercial.',
    icon: Mic2,
  },
];

export const OMNI_SERVICE_MAP: Record<ServiceId, OmniServiceDescriptor> = OMNI_SERVICES.reduce(
  (acc, item) => {
    acc[item.id] = item;
    return acc;
  },
  {} as Record<ServiceId, OmniServiceDescriptor>,
);
