import { NextRequest, NextResponse } from 'next/server';
import { getActiveConfig } from '@/lib/agent/optimizer/activeConfig';
import { composeElevenLabsMusic, hasElevenLabsMusicKey } from '@/lib/elevenlabs/music';
import { generateMusicCover, generateVoiceSong, generateMusic } from '@/lib/ai/replicate';
import { generateUdioTrack } from '@/lib/udio/client';
import { hasUdioApiKey } from '@/lib/chat/mediaKeys';
import { trimAudioToDuration } from '@/lib/audio/trimAudio';
import { transcodeVoiceToMp3 } from '@/lib/audio/transcode';
import { convertSongWithRvc } from '@/lib/audio/rvc';
import { getUserVoiceModel, DEMO_VOICE_USER_ID } from '@/lib/audio/voiceModel';
import { uploadAndSign, createSignedAssetUrl } from '@/lib/orchestrator/storage-adapter';
import { authedClientFromRequest } from '@/lib/supabase/server';
import { recordCompletedAsset } from '@/lib/orchestrator/jobs';
import { runWithLatencyFailover, type ProviderAttempt } from '@/lib/providers/latencyFailover';
import { isProviderTripped, recordProviderResult } from '@/lib/orchestrator/idempotency';
import { randomUUID } from 'node:crypto';
import { checkRateLimit, RATE_LIMITS } from '@/lib/api/rate-limit';
import { deductCredits, hasSufficientBalance } from '@/lib/orchestrator/ledger';
import { creditCostFor } from '@/lib/credits/pricing';

/**
 * Assistant music generation.
 *
 * POST { prompt } → { success, url }. The Smart Assistant's Music mode sends a
 * vibe/description here; a track is composed and RE-HOSTED to Supabase Storage
 * (CSP media-src allows *.supabase.co) so the <audio> element plays + the track
 * persists past the provider's short-lived CDN URL.
 *
 * Provider chain (composeTrackUrl): Udio (DEFAULT primary when UDIO_API_KEY is set —
 * the founder's funded song engine) → ElevenLabs Music (sung when not instrumental) →
 * Replicate MusicGen (instrumental last resort). Set MUSIC_PROVIDER=elevenlabs to skip
 * Udio. Singer gender is prompt-engineered (the EL Music + Udio APIs take no voice_id;
 * cloned voice IDs apply to TTS/narration, not music generation).
 *
 * Synchronous start+poll, bounded WELL under the 300s function ceiling. Fail-closed
 * with a clean reason on a real miss; fail-open on the re-host (keeps the provider URL).
 */

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';
export const maxDuration = 300;

// Host a data: reference track to a signed https URL — Replicate MusicGen fetches the
// melody by URL, so an uploaded audio file is copied to Supabase first. Fail-open → null.
async function hostAudioReference(dataUrl: string): Promise<string | null> {
  try {
    const m = dataUrl.match(/^data:([^;,]+)[;,]/);
    const mime = (m?.[1] || 'audio/mpeg').toLowerCase();
    const ext = /wav/i.test(mime) ? 'wav' : /ogg/i.test(mime) ? 'ogg' : /mp4|m4a|aac/i.test(mime) ? 'm4a' : 'mp3';
    const b64 = dataUrl.includes(',') ? dataUrl.split(',')[1] ?? '' : '';
    if (!b64) return null;
    const path = `omni-music-ref/${Date.now()}-${Math.random().toString(36).slice(2, 8)}.${ext}`;
    return (await uploadAndSign('uploads', path, b64, mime, 7200)) || null;
  } catch {
    return null;
  }
}

// Suno-style album cover art for a generated track — themed to the brief + genre, so
// the visual matches the song. Square, text-free. Fail-open → null (no cover).
//
// COST: the cover image is generated by Pollinations.ai (FLUX) — a free, key-less
// image endpoint that renders on a plain GET — instead of the paid NanoBanana 2K
// model. It is fetched SERVER-SIDE (so no browser-CSP concern) and re-hosted to a
// CSP-allowed Supabase signed URL exactly as before, so the result card + Library
// keep a persistent https cover. Pollinations renders on demand (can take ~15-45s),
// so it runs in PARALLEL with the (slower) track and still lands before the song.
async function generateCoverArt(songPrompt: string, style: string): Promise<string | null> {
  try {
    const coverPrompt = `Album cover art for a ${style || 'cinematic'} music track. Mood and theme: ${songPrompt.slice(0, 220)}. Evocative, atmospheric, striking, professional album artwork, square composition, high detail. No text, no words, no letters, no captions, no logos.`;
    // Deterministic-ish seed for variety run-to-run; flux model for quality.
    const seed = Math.floor(Math.random() * 1_000_000);
    const url =
      `https://image.pollinations.ai/prompt/${encodeURIComponent(coverPrompt)}` +
      `?width=1024&height=1024&nologo=true&model=flux&seed=${seed}`;
    // Pollinations generates the image during the request → allow a generous window.
    const ac = new AbortController();
    const to = setTimeout(() => ac.abort(), 60_000);
    const r = await fetch(url, { signal: ac.signal }).finally(() => clearTimeout(to));
    if (!r.ok) return null;
    const ct = r.headers.get('content-type') || 'image/jpeg';
    // Guard: on overload Pollinations can return an HTML/text error page — only accept images.
    if (!/^image\//i.test(ct)) return null;
    const ext = /png/i.test(ct) ? 'png' : /webp/i.test(ct) ? 'webp' : 'jpg';
    const buf = Buffer.from(await r.arrayBuffer());
    if (!buf.byteLength || buf.byteLength > 18 * 1024 * 1024) return null;
    // Re-host to a CSP-allowed Supabase signed URL (7-day) so the cover renders + persists.
    const path = `omni-music-cover/${Date.now()}-${Math.random().toString(36).slice(2, 8)}.${ext}`;
    return (await uploadAndSign('uploads', path, buf.toString('base64'), ct, 604800)) || null;
  } catch {
    return null;
  }
}

// v330 — standalone music composition via ElevenLabs Music (the master audio engine,
// replacing Udio), with Replicate MusicGen as the graceful fallback. EL Music returns
// audio BYTES, so they're hosted to Supabase first; the result is always a fetchable URL.
async function composeTrackUrl(prompt: string, style: string, instrumental: boolean, lengthSec = 30): Promise<{ url: string; engine: string }> {
  // FIX 2 — lengthSec === 0 means "full song": keep Udio's full ~2–4 min output (no
  // trim). Otherwise clamp to a 15–90s window. secs===0 is the skip-trim sentinel.
  const secs = lengthSec === 0 ? 0 : Math.max(15, Math.min(90, Math.round(lengthSec) || 30));
  // Udio ignores length (it returns a full ~2–4 min song), so secs===0 is Udio's "full song"
  // sentinel. But EL Music and MusicGen REQUIRE an explicit length — passing 0 there returns a
  // ~3s clip (audit HIGH: "full song" was broken on the primary engine). Map the sentinel to a
  // real full-song target for those engines, bounded well under the 300s function budget.
  const elMusicSec = secs === 0 ? 120 : secs; // ElevenLabs Music: ~2-min full song
  const musicgenSec = secs === 0 ? 90 : secs; // MusicGen fallback: bounded so it finishes in time

  type Track = { url: string; engine: string };

  // Each provider's EXACT existing logic, now expressed as a failover attempt. Order is
  // unchanged: Udio (funded primary) → ElevenLabs Music → MusicGen. The chain is run
  // through runWithLatencyFailover so a provider that ERRORS *or* exceeds its latency
  // BUDGET (a "heavy bottleneck") reroutes to the next — sequentially, one at a time,
  // so at most one provider serves the track (no double-submit). Fully fail-open: if the
  // whole chain is exhausted we throw the same error the sequential version did.
  const udioRun = async (): Promise<Track> => {
    const udio = await generateUdioTrack(
      { prompt: style ? `${prompt}. Style: ${style}.` : prompt, style, makeInstrumental: instrumental },
      { maxAttempts: 45, pollIntervalMs: 4000 }, // ~180s, bounded under the 300s ceiling
    );
    if (udio.status === 'succeeded' && udio.audioUrl) {
      // Udio ignores the requested length (no duration param) → full ~2–4 min song. Trim
      // to `secs` (30/60/90) so the panel selection is honoured — UNLESS secs===0 ("full
      // song"). Fail-open: if the trim misses, keep the full track.
      if (secs > 0) {
        const trimmed = await trimAudioToDuration(udio.audioUrl, secs);
        return { url: trimmed ?? udio.audioUrl, engine: 'Udio' }; // re-hosted by caller
      }
      return { url: udio.audioUrl, engine: 'Udio' }; // full song — no trim
    }
    throw new Error(`Udio did not complete (${udio.status})`);
  };
  const elRun = async (): Promise<Track> => {
    const { audio, contentType } = await composeElevenLabsMusic({
      prompt: style ? `${prompt}. Style: ${style}.` : prompt,
      lengthMs: elMusicSec * 1000,
      instrumental,
    });
    const path = `omni-music/${Date.now()}-${Math.random().toString(36).slice(2, 8)}.mp3`;
    const url = await uploadAndSign('uploads', path, audio.toString('base64'), contentType, 604800);
    if (url) return { url, engine: 'ElevenLabs Music' };
    throw new Error('ElevenLabs Music host failed');
  };
  const musicgenRun = async (): Promise<Track> => {
    const score = await generateMusic(style ? `${prompt}, ${style}` : prompt, musicgenSec);
    if (score.audioUrl) return { url: score.audioUrl, engine: 'MusicGen' };
    throw new Error('MusicGen did not complete in time');
  };

  // Per-provider latency budgets (env-tunable, no deploy needed). Udio's is set just above
  // its own ~180s internal poll cap so a normal run is UNAFFECTED — the budget only trips on
  // a true hang; EL/MusicGen budgets bound the fallbacks well under the 300s function ceiling.
  const num = (v: string | undefined, d: number) => { const n = Number(v); return Number.isFinite(n) && n > 0 ? n : d; };
  const providers: ProviderAttempt<Track>[] = [];
  if (hasUdioApiKey() && process.env.MUSIC_PROVIDER !== 'elevenlabs') {
    providers.push({ name: 'udio', budgetMs: num(process.env.MUSIC_UDIO_BUDGET_MS, 190_000), run: udioRun });
  }
  if (hasElevenLabsMusicKey()) {
    providers.push({ name: 'elevenlabs-music', budgetMs: num(process.env.MUSIC_EL_BUDGET_MS, 90_000), run: elRun });
  }
  providers.push({ name: 'musicgen', budgetMs: num(process.env.MUSIC_MUSICGEN_BUDGET_MS, 100_000), run: musicgenRun });

  // Pre-read the Redis circuit breaker ONCE (it's async; the failover's isTripped is sync)
  // so a provider already tripped by recent failures is skipped without spending its budget.
  const trippedSet = new Set<string>();
  await Promise.all(providers.map(async (p) => { try { if (await isProviderTripped(p.name)) trippedSet.add(p.name); } catch { /* fail-open */ } }));

  const res = await runWithLatencyFailover<Track>(providers, {
    isTripped: (n) => trippedSet.has(n),
    record: (n, ok) => { void recordProviderResult(n, ok); },
    onReroute: ({ from, to, reason }) => {
      // eslint-disable-next-line no-console
      console.warn(`[ai/music] ${from} ${reason} → ${to ?? 'exhausted'}`);
    },
  });
  if (res.ok && res.result) return res.result;
  throw new Error('Music generation did not complete in time.');
}

export async function POST(req: NextRequest) {
  const rl = await checkRateLimit(req, RATE_LIMITS.EXPENSIVE);
  if (rl) return rl;

  let prompt = '';
  let style = 'cinematic';
  let makeInstrumental = true;
  let lyrics = '';
  let audioReference = '';
  let voiceReference = '';
  let useMyVoice = false;
  let durationSec = 30;
  let tempo = '';
  let voiceType: 'female' | 'male' | 'duet' | '' = '';
  // DURABLE PROGRESS — the composer's tray jobId. When present the completed row is UPSERTED
  // under this id (converging with the client's placeholder) so a track produces ONE
  // generation_jobs row, not a client + server duplicate.
  let clientJobId = '';
  try {
    const body = (await req.json().catch(() => ({}))) as { prompt?: unknown; style?: unknown; instrumental?: unknown; lyrics?: unknown; audioReference?: unknown; voiceReference?: unknown; useMyVoice?: unknown; durationSec?: unknown; tempo?: unknown; voiceType?: unknown; jobId?: unknown };
    if (typeof body.jobId === 'string') clientJobId = body.jobId.slice(0, 120);
    prompt = typeof body.prompt === 'string' ? body.prompt.trim() : '';
    if (typeof body.style === 'string' && body.style.trim()) style = body.style.trim();
    if (typeof body.instrumental === 'boolean') makeInstrumental = body.instrumental;
    // P6 — duration (15/30/60/90) + tempo (slow/medium/fast). Duration drives the track
    // length; tempo is folded into the prompt as a BPM/feel hint the model honours.
    // FIX 2 — durationSec === 0 → "full song" (keep Udio's full output, no trim);
    // any positive value clamps to the 15–90s window.
    if (typeof body.durationSec === 'number') durationSec = body.durationSec === 0 ? 0 : Math.max(15, Math.min(90, Math.round(body.durationSec)));
    if (typeof body.tempo === 'string') tempo = body.tempo.trim().toLowerCase();

    // PRE-RENDER balance gate — block a paid MusicGen/EL call for a user who can't afford it
    // (else a 0-balance user generates unlimited free tracks). Authed only; fail-open.
    try {
      const { user: gateUser } = await authedClientFromRequest(req);
      if (gateUser?.id && !(await hasSufficientBalance(gateUser.id, creditCostFor('music', { seconds: durationSec })))) {
        return NextResponse.json({ success: false, error: 'არასაკმარისი კრედიტი — შეავსე ბალანსი. / Not enough credits — please top up.', code: 'insufficient_credits' }, { status: 402 });
      }
    } catch { /* fail-open — the post-success deduct remains the backstop */ }
    // Custom lyrics (vocal tracks) — Udio sings these verbatim; empty → auto lyrics.
    if (typeof body.lyrics === 'string' && body.lyrics.trim()) lyrics = body.lyrics.trim().slice(0, 2000);
    // Cover: an uploaded reference track (data: URL) → Udio reimagines it in the
    // requested style/prompt.
    // data: (small fallback) | https URL | storage path (browser-uploaded) — the
    // cover branch resolves each to a fetchable melody URL.
    if (typeof body.audioReference === 'string' && body.audioReference.trim()) audioReference = body.audioReference.trim();
    // Voice clone: an uploaded sample of the USER'S voice (>15s, data:/https/path) →
    // MiniMax sings the lyrics in that voice. Highest-priority branch below.
    if (typeof body.voiceReference === 'string' && body.voiceReference.trim()) voiceReference = body.voiceReference.trim();
    // Use the user's TRAINED RVC voice (faithful) instead of a one-shot reference.
    if (body.useMyVoice === true) useMyVoice = true;
    // Sung-vocal gender for a SONG → appended to the prompt as vocal descriptors
    // (the music engine is prompt-steered for the singer; see vocalDescriptor below).
    if (body.voiceType === 'female' || body.voiceType === 'male' || body.voiceType === 'duet') voiceType = body.voiceType;
  } catch {
    /* malformed body → guard below */
  }

  if (!prompt) {
    return NextResponse.json({ success: false, error: 'prompt is required' }, { status: 400 });
  }

  // Fold the tempo selection into the brief as a feel/BPM hint (empty for 'medium').
  const tempoHint = tempo === 'slow' ? 'Slow tempo, around 70 BPM. ' : tempo === 'fast' ? 'Fast, upbeat tempo, around 140 BPM. ' : '';
  let capped = (tempoHint + prompt).slice(0, 1000);
  // SELF-IMPROVING (STEP 5): if an admin has APPROVED an active 'audio' config, apply its learned
  // prompt directive as a suffix so the loop's improvement reaches generation. Fail-soft.
  const activeAudioCfg = await getActiveConfig('audio').catch(() => null);
  if (activeAudioCfg?.prompt) capped = `${capped} ${activeAudioCfg.prompt}`;

  // Sung-vocal gender → prompt engineering. The music engine (ElevenLabs Music /
  // MusicGen) is steered by the text prompt, so the singer's gender rides in the
  // brief. Only meaningful for a SONG (non-instrumental).
  const vocalDescriptor =
    !makeInstrumental && voiceType
      ? voiceType === 'female'
        ? 'female vocals, female singer'
        : voiceType === 'male'
          ? 'male vocals, male singer'
          : 'male and female duet, two voices'
      : '';

  try {
    // Suno-style cover art — generated in PARALLEL with the track (it's the faster of
    // the two, so it adds no latency) and themed to the song's brief + genre.
    const coverArtPromise = generateCoverArt(capped, style);

    // COVER vs compose: with an uploaded reference track, REPLICATE MusicGen-melody
    // re-imagines it in the requested style (conditioned on the track's melody);
    // otherwise Udio composes a fresh track from the brief.
    let providerAudioUrl = '';
    // The engine that actually produced the track → returned to the client for an
    // honest "Generated with …" badge (the chain is runtime-dependent, so we can't
    // hardcode it). Defaults updated per branch below.
    let engine = 'AI';
    const trainedModel = useMyVoice ? await (async () => { try { const { user } = await authedClientFromRequest(req); return await getUserVoiceModel(user?.id ?? DEMO_VOICE_USER_ID); } catch { return null; } })() : null;
    if (trainedModel) {
      // FAITHFUL "sing in my voice": ElevenLabs Music composes a song WITH vocals, then
      // realistic-voice-cloning (RVC) swaps those vocals for the user's TRAINED model.
      // Fail-open: if the convert misses, return the composed song so the user still gets a track.
      const composed = await composeTrackUrl(lyrics ? `${capped}. Lyrics: ${lyrics}` : capped, style, false, durationSec);
      try {
        providerAudioUrl = await convertSongWithRvc(composed.url, trainedModel.modelUrl);
        engine = 'Your Voice (RVC)';
      } catch {
        providerAudioUrl = composed.url;
        engine = composed.engine;
      }
    } else if (voiceReference) {
      // "Create a song in MY voice" — resolve the user's uploaded voice sample to an
      // https URL (data: → host · https → use · path → sign the browser upload) and
      // have MiniMax sing the lyrics in that voice (zero-shot, ## adds accompaniment).
      const voiceUrl = voiceReference.startsWith('data:')
        ? await hostAudioReference(voiceReference)
        : /^https?:\/\//i.test(voiceReference)
          ? voiceReference
          : await createSignedAssetUrl(process.env.UPLOAD_BUCKET || 'uploads', voiceReference, 3600);
      if (!voiceUrl) {
        return NextResponse.json({ success: false, error: 'Could not process the voice file.' }, { status: 502 });
      }
      // Normalize the clip to MP3 first — the browser records webm/mp4 and users upload
      // m4a/ogg, none of which MiniMax reliably accepts ("doesn't generate"). Fail-open:
      // if transcoding hiccups we still try the original (works when it was already wav/mp3).
      const mp3Voice = await transcodeVoiceToMp3(voiceUrl);
      // Lyrics are what MiniMax sings; fall back to the brief if the user only gave a vibe.
      const song = await generateVoiceSong(lyrics || capped, { voiceUrl: mp3Voice || voiceUrl });
      providerAudioUrl = song.audioUrl;
      engine = 'MiniMax (your voice)';
    } else if (audioReference) {
      // Resolve the melody to an https URL Replicate can fetch:
      //  • data:  → host it (small fallback)
      //  • https  → use directly
      //  • path   → a storage object uploaded by the browser via /api/upload/sign
      //             (bypasses the function-body limit); sign a readable URL now that
      //             the object exists.
      const melodyUrl = audioReference.startsWith('data:')
        ? await hostAudioReference(audioReference)
        : /^https?:\/\//i.test(audioReference)
          ? audioReference
          : await createSignedAssetUrl(process.env.UPLOAD_BUCKET || 'uploads', audioReference, 3600);
      if (!melodyUrl) {
        return NextResponse.json({ success: false, error: 'Could not process the reference audio.' }, { status: 502 });
      }
      const styledPrompt = style ? `${capped}, ${style} style` : capped;
      const cover = await generateMusicCover(styledPrompt, melodyUrl, 30);
      providerAudioUrl = cover.audioUrl;
      engine = 'MusicGen (cover)';
    } else {
      // Compose a fresh track from the brief — ElevenLabs Music (sung when not
      // instrumental), MusicGen fallback. Lyrics, if given, steer the prompt; the
      // vocal descriptor (female/male/duet) is appended for a sung track.
      const composeBrief = vocalDescriptor ? `${capped}. ${vocalDescriptor}.` : capped;
      const composed = await composeTrackUrl(lyrics ? `${composeBrief}. Lyrics: ${lyrics}` : composeBrief, style, makeInstrumental, durationSec);
      providerAudioUrl = composed.url;
      engine = composed.engine;
    }

    // RE-HOST to Supabase so the audio plays in-app (CSP-allowed) + persists.
    let hostedUrl = providerAudioUrl;
    try {
      const ac = new AbortController();
      const to = setTimeout(() => ac.abort(), 25_000);
      const r = await fetch(providerAudioUrl, { signal: ac.signal }).finally(() => clearTimeout(to));
      if (r.ok) {
        const ct = r.headers.get('content-type') || 'audio/mpeg';
        const ext = /wav/i.test(ct) ? 'wav' : 'mp3';
        const b64 = Buffer.from(await r.arrayBuffer()).toString('base64');
        const path = `omni-music/${Date.now()}-${Math.random().toString(36).slice(2, 8)}.${ext}`;
        const signed = await uploadAndSign('uploads', path, b64, ct, 604800); // 7-day signed URL
        if (signed) hostedUrl = signed;
      }
    } catch {
      /* fail-open — keep the provider URL */
    }

    // File the track into the Library — under the signed-in user, or the shared demo
    // identity when testing without sign-in (so anonymous generations still show up).
    try {
      const { user } = await authedClientFromRequest(req);
      if (user?.id) {
        // BILLING FIX — this DIRECT route bypassed providerRouter's post-success charge, so chat
        // music mode generated for FREE (same leak class as the image route). Charge the
        // balance-of-record via the idempotent deduct_credits RPC, cost by duration. Idempotent per
        // tray jobId; rejects overdraw; best-effort AFTER success so a ledger hiccup never fails the track.
        await deductCredits(user.id, creditCostFor('music', { seconds: durationSec }), `music:${clientJobId || hostedUrl}:${user.id}`)
          .catch(() => { /* best-effort — the asset is already delivered */ });
      }
      // Reuse the composer's tray jobId so this completion UPSERTS the client's placeholder
      // row (one row, no duplicate); direct/other callers still get a fresh UUID.
      await recordCompletedAsset({ id: clientJobId || randomUUID(), userId: user?.id ?? DEMO_VOICE_USER_ID, serviceType: 'music', url: hostedUrl, prompt: capped });
    } catch {
      /* fail-open */
    }

    // The cover finished while the track generated — attach it for the result card.
    const coverUrl = await coverArtPromise;
    return NextResponse.json({ success: true, url: hostedUrl, engine, ...(coverUrl ? { coverUrl } : {}) });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Music generation failed';
    // eslint-disable-next-line no-console
    console.error('[ai/music]', message);
    return NextResponse.json({ success: false, error: message }, { status: 502 });
  }
}
