export interface ServiceDefinition {
  slug: string;
  title: string;
  href: string;
  id: string;
  name: string;
  description: string;
  icon: string;
  route: string;
  enabled: boolean;
}

export const SERVICE_REGISTRY: ServiceDefinition[] = [
  {
    slug: 'online-shop',
    title: 'Online Shop',
    href: '/services/online-shop',
    id: 'online-shop',
    name: 'Online Shop',
    description: 'Launch and operate your commerce storefront with fulfillment-ready workflows.',
    icon: '🛍️',
    route: '/services/online-shop',
    enabled: true,
  },
  {
    slug: 'avatar-builder',
    title: 'Avatar Builder',
    href: '/services/avatar-builder',
    id: 'avatar-builder',
    name: 'Avatar Builder',
    description: 'Create and manage your premium digital identity.',
    icon: '🧑',
    route: '/services/avatar-builder',
    enabled: true,
  },
  {
    slug: 'music-studio',
    title: 'Music Studio',
    href: '/services/music-studio',
    id: 'music-studio',
    name: 'Music Studio',
    description: 'Generate songs, stems, and production-ready audio drafts.',
    icon: '🎵',
    route: '/services/music-studio',
    enabled: true,
  },
  {
    slug: 'video-studio',
    title: 'Video Studio',
    href: '/services/video-studio',
    id: 'video-studio',
    name: 'Video Studio',
    description: 'Produce cinematic video sequences from guided prompts.',
    icon: '🎬',
    route: '/services/video-studio',
    enabled: true,
  },
  {
    slug: 'media-production',
    title: 'Media Production',
    href: '/services/media-production',
    id: 'media-production',
    name: 'Media Production',
    description: 'Build complete multimedia outputs for campaigns and storytelling.',
    icon: '📽️',
    route: '/services/media-production',
    enabled: true,
  },
  {
    slug: 'visual-intelligence',
    title: 'Visual Intelligence',
    href: '/services/visual-intelligence',
    id: 'visual-intelligence',
    name: 'Visual Intelligence',
    description: 'Analyze and orchestrate visual assets with AI-assisted decision support.',
    icon: '🧠',
    route: '/services/visual-intelligence',
    enabled: true,
  },
  {
    slug: 'image-creator',
    title: 'Image Creator',
    href: '/services/image-creator',
    id: 'image-creator',
    name: 'Image Creator',
    description: 'Generate design-ready visuals and concept imagery at scale.',
    icon: '🖼️',
    route: '/services/image-creator',
    enabled: true,
  },
  {
    slug: 'agent-g',
    title: 'Agent G',
    href: '/services/agent-g',
    id: 'agent-g',
    name: 'Agent G',
    description: 'Coordinate autonomous workflows across your AI workspace.',
    icon: '🤖',
    route: '/services/agent-g',
    enabled: true,
  },
  {
    slug: 'social-media-manager',
    title: 'Social Media Manager',
    href: '/services/social-media-manager',
    id: 'social-media-manager',
    name: 'Social Media Manager',
    description: 'Create social content pipelines and publishing-ready outputs.',
    icon: '📣',
    route: '/services/social-media-manager',
    enabled: true,
  },
  {
    slug: 'prompt-builder',
    title: 'Prompt Builder',
    href: '/services/prompt-builder',
    id: 'prompt-builder',
    name: 'Prompt Builder',
    description: 'Design reusable prompt systems for consistent AI performance.',
    icon: '🧩',
    route: '/services/prompt-builder',
    enabled: true,
  },
  {
    slug: 'text-intelligence',
    title: 'Text Intelligence',
    href: '/services/text-intelligence',
    id: 'text-intelligence',
    name: 'Text Intelligence',
    description: 'Generate, optimize, and analyze strategic text content.',
    icon: '📝',
    route: '/services/text-intelligence',
    enabled: true,
  },
  {
    slug: 'photo-studio',
    title: 'Photo Studio',
    href: '/services/photo-studio',
    id: 'photo-studio',
    name: 'Photo Studio',
    description: 'Create editorial photo outputs and campaign image sets.',
    icon: '📸',
    route: '/services/photo-studio',
    enabled: true,
  },
  {
    slug: 'marketplace',
    title: 'Marketplace',
    href: '/services/marketplace',
    id: 'marketplace',
    name: 'Marketplace',
    description: 'Manage listings, discovery, and conversion paths in one place.',
    icon: '🏪',
    route: '/services/marketplace',
    enabled: true,
  },
  {
    slug: 'business-agent',
    title: 'Business Agent',
    href: '/services/business-agent',
    id: 'business-agent',
    name: 'Business Agent',
    description: 'Automate business operations and growth workflows.',
    icon: '💼',
    route: '/services/business-agent',
    enabled: true,
  },
  {
    slug: 'game-creator',
    title: 'Game Creator',
    href: '/services/game-creator',
    id: 'game-creator',
    name: 'Game Creator',
    description: 'Prototype playable interactive concepts with AI assistance.',
    icon: '🎮',
    route: '/services/game-creator',
    enabled: true,
  },
  {
    slug: 'voice-lab',
    title: 'Voice Lab',
    href: '/services/voice-lab',
    id: 'voice-lab',
    name: 'Voice Lab',
    description: 'Build speech outputs, voice clones, and audio narration flows.',
    icon: '🎙️',
    route: '/services/voice-lab',
    enabled: true,
  },
];
