export interface Service {
  id: string;
  route: string;
  nameKa: string;
  nameEn: string;
  icon: string;
  descriptionKa: string;
  descriptionEn: string;
  ctaPrimaryKa: string;
  ctaPrimaryEn: string;
  ctaSecondaryKa: string;
  ctaSecondaryEn: string;
  pricing?: {
    amount: number;
    currency: string;
    period: string;
  };
}

export const services: Service[] = [
  {
    id: "agent-g",
    route: "/agent-g",
    nameKa: "Agent G",
    nameEn: "Agent G",
    icon: "🤖",
    descriptionKa: "პერსონალური AI აგენტი სრული კონტროლით",
    descriptionEn: "Personal AI agent with full control",
    ctaPrimaryKa: "აქტივაცია",
    ctaPrimaryEn: "Activate",
    ctaSecondaryKa: "უკან სამუშაო არეში",
    ctaSecondaryEn: "Back to Workspace",
    pricing: {
      amount: 2000,
      currency: "GEL",
      period: "Year",
    },
  },
  {
    id: "avatar-builder",
    route: "/avatar-builder",
    nameKa: "Avatar Builder",
    nameEn: "Avatar Builder",
    icon: "👤",
    descriptionKa: "შექმენი რეალისტური AI ავატარები",
    descriptionEn: "Create realistic AI avatars",
    ctaPrimaryKa: "შექმნა დაწყება",
    ctaPrimaryEn: "Start Creating",
    ctaSecondaryKa: "უკან სამუშაო არეში",
    ctaSecondaryEn: "Back to Workspace",
  },
  {
    id: "voice-lab",
    route: "/voice-lab",
    nameKa: "Voice Lab",
    nameEn: "Voice Lab",
    icon: "🎙️",
    descriptionKa: "AI ხმის გენერაცია და კლონირება",
    descriptionEn: "AI voice generation and cloning",
    ctaPrimaryKa: "ხმის შექმნა",
    ctaPrimaryEn: "Create Voice",
    ctaSecondaryKa: "უკან სამუშაო არეში",
    ctaSecondaryEn: "Back to Workspace",
  },
  {
    id: "image-architect",
    route: "/image-architect",
    nameKa: "Image Architect",
    nameEn: "Image Architect",
    icon: "🎨",
    descriptionKa: "პროფესიონალური სურათების გენერაცია",
    descriptionEn: "Professional image generation",
    ctaPrimaryKa: "გენერაცია",
    ctaPrimaryEn: "Generate",
    ctaSecondaryKa: "უკან სამუშაო არეში",
    ctaSecondaryEn: "Back to Workspace",
  },
  {
    id: "music-studio",
    route: "/music-studio",
    nameKa: "Music Studio",
    nameEn: "Music Studio",
    icon: "🎵",
    descriptionKa: "AI მუსიკის შექმნა და პროდუცირება",
    descriptionEn: "AI music creation and production",
    ctaPrimaryKa: "მუსიკის შექმნა",
    ctaPrimaryEn: "Create Music",
    ctaSecondaryKa: "უკან სამუშაო არეში",
    ctaSecondaryEn: "Back to Workspace",
  },
  {
    id: "video-cine-lab",
    route: "/video-cine-lab",
    nameKa: "Video Cine Lab",
    nameEn: "Video Cine Lab",
    icon: "🎬",
    descriptionKa: "კინემატოგრაფიული ვიდეოების შექმნა",
    descriptionEn: "Cinematic video creation",
    ctaPrimaryKa: "ვიდეოს შექმნა",
    ctaPrimaryEn: "Create Video",
    ctaSecondaryKa: "უკან სამუშაო არეში",
    ctaSecondaryEn: "Back to Workspace",
  },
  {
    id: "game-forge",
    route: "/game-forge",
    nameKa: "Game Forge",
    nameEn: "Game Forge",
    icon: "🎮",
    descriptionKa: "AI თამაშების დიზაინი და შექმნა",
    descriptionEn: "AI game design and creation",
    ctaPrimaryKa: "თამაშის შექმნა",
    ctaPrimaryEn: "Create Game",
    ctaSecondaryKa: "უკან სამუშაო არეში",
    ctaSecondaryEn: "Back to Workspace",
  },
  {
    id: "ai-production",
    route: "/ai-production",
    nameKa: "AI Production",
    nameEn: "AI Production",
    icon: "🎯",
    descriptionKa: "სრული AI პროდუქციის მართვა",
    descriptionEn: "Complete AI production management",
    ctaPrimaryKa: "პროექტის დაწყება",
    ctaPrimaryEn: "Start Project",
    ctaSecondaryKa: "უკან სამუშაო არეში",
    ctaSecondaryEn: "Back to Workspace",
  },
  {
    id: "business-agent",
    route: "/business-agent",
    nameKa: "Business Agent",
    nameEn: "Business Agent",
    icon: "💼",
    descriptionKa: "ბიზნეს ავტომატიზაცია AI-ით",
    descriptionEn: "Business automation with AI",
    ctaPrimaryKa: "აქტივაცია",
    ctaPrimaryEn: "Activate",
    ctaSecondaryKa: "უკან სამუშაო არეში",
    ctaSecondaryEn: "Back to Workspace",
  },
  {
    id: "prompt-builder",
    route: "/prompt-builder",
    nameKa: "Prompt Builder",
    nameEn: "Prompt Builder",
    icon: "📝",
    descriptionKa: "პროფესიონალური პრომპტების შექმნა",
    descriptionEn: "Professional prompt creation",
    ctaPrimaryKa: "პრომპტის შექმნა",
    ctaPrimaryEn: "Build Prompt",
    ctaSecondaryKa: "უკან სამუშაო არეში",
    ctaSecondaryEn: "Back to Workspace",
  },
  {
    id: "image-generator",
    route: "/image-generator",
    nameKa: "Image Generator",
    nameEn: "Image Generator",
    icon: "🖼️",
    descriptionKa: "სწრაფი სურათების გენერაცია",
    descriptionEn: "Quick image generation",
    ctaPrimaryKa: "გენერაცია",
    ctaPrimaryEn: "Generate",
    ctaSecondaryKa: "უკან სამუშაო არეში",
    ctaSecondaryEn: "Back to Workspace",
  },
  {
    id: "video-generator",
    route: "/video-generator",
    nameKa: "Video Generator",
    nameEn: "Video Generator",
    icon: "📹",
    descriptionKa: "სწრაფი ვიდეოების გენერაცია",
    descriptionEn: "Quick video generation",
    ctaPrimaryKa: "ვიდეოს შექმნა",
    ctaPrimaryEn: "Create Video",
    ctaSecondaryKa: "უკან სამუშაო არეში",
    ctaSecondaryEn: "Back to Workspace",
  },
  {
    id: "text-intelligence",
    route: "/text-intelligence",
    nameKa: "Text Intelligence",
    nameEn: "Text Intelligence",
    icon: "📄",
    descriptionKa: "ტექსტის ანალიზი და გენერაცია",
    descriptionEn: "Text analysis and generation",
    ctaPrimaryKa: "ანალიზის დაწყება",
    ctaPrimaryEn: "Start Analysis",
    ctaSecondaryKa: "უკან სამუშაო არეში",
    ctaSecondaryEn: "Back to Workspace",
  },
];
