'use client'

import { useState, memo } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { useLanguage } from '@/lib/i18n/LanguageContext'

type Lang = 'en' | 'ka' | 'ru'

const COPY = {
  en: {
    eyebrow: 'SEE WHAT AI CAN DO',
    title: 'From Prompt to Production',
    sub: 'Real AI outputs generated by MyAvatar.ge services — from a single prompt.',
  },
  ka: {
    eyebrow: 'ნახე რას აკეთებს AI',
    title: 'პრომპტიდან პროდაქშენამდე',
    sub: 'რეალური AI შედეგები, რომლებიც MyAvatar.ge სერვისებმა შექმნეს — ერთი პრომპტით.',
  },
  ru: {
    eyebrow: 'СМОТРИТЕ, ЧТО МОЖЕТ AI',
    title: 'От промпта до продакшна',
    sub: 'Реальные AI-результаты, созданные сервисами MyAvatar.ge — из одного промпта.',
  },
} as const

interface DemoItem {
  id: string
  service: string
  icon: string
  accent: string
  prompt: { en: string; ka: string; ru: string }
  outputType: 'image' | 'video' | 'audio' | 'text'
  mockOutput: { en: string; ka: string; ru: string }
}

const DEMOS: DemoItem[] = [
  {
    id: 'avatar-demo', service: 'Avatar Studio', icon: '👤', accent: '#a78bfa',
    prompt: { en: '"Create a professional headshot for a tech CEO"', ka: '"შექმენი პროფესიონალური პორტრეტი ტექ-დირექტორისთვის"', ru: '"Создай профессиональный портрет для тех-директора"' },
    outputType: 'image',
    mockOutput: { en: 'AI-generated professional headshot with studio lighting, natural expression, corporate style', ka: 'AI-ით გენერირებული პროფესიონალური პორტრეტი სტუდიური განათებით', ru: 'AI-сгенерированный профессиональный портрет со студийным светом' },
  },
  {
    id: 'video-demo', service: 'Video Generation', icon: '🎬', accent: '#f59e0b',
    prompt: { en: '"Cinematic drone fly-over of a futuristic city at sunset"', ka: '"კინემატოგრაფიული დრონ-ვიდეო ფუტურისტულ ქალაქზე მზის ჩასვლისას"', ru: '"Кинематографический полёт дрона над футуристическим городом на закате"' },
    outputType: 'video',
    mockOutput: { en: '4K cinematic video — atmospheric lighting, volumetric clouds, neon city reflections', ka: '4K კინემატოგრაფიული ვიდეო — ატმოსფერული განათება, ნეონური ასახვები', ru: '4K кинематографическое видео — атмосферное освещение, неоновые отражения' },
  },
  {
    id: 'image-demo', service: 'Image Generation', icon: '🖼️', accent: '#f472b6',
    prompt: { en: '"Product shot of a luxury perfume bottle on marble"', ka: '"ლუქს პარფიუმერიის ბოთლის პროდუქტ-ფოტო მარმარილოზე"', ru: '"Продуктовое фото флакона люксовых духов на мраморе"' },
    outputType: 'image',
    mockOutput: { en: 'Advertising-grade product photography — soft reflections, premium composition, 4K resolution', ka: 'სარეკლამო დონის პროდუქტის ფოტო — რბილი ასახვები, პრემიუმ კომპოზიცია', ru: 'Рекламное фото продукта — мягкие отражения, премиум-композиция' },
  },
  {
    id: 'music-demo', service: 'Music Production', icon: '🎵', accent: '#34d399',
    prompt: { en: '"Epic orchestral cinematic trailer music, 90 BPM"', ka: '"ეპიკური ორკესტრული კინო-ტრეილერის მუსიკა, 90 BPM"', ru: '"Эпическая оркестровая музыка для трейлера, 90 BPM"' },
    outputType: 'audio',
    mockOutput: { en: 'Original orchestral score — strings, brass, percussion, with cinematic build-up', ka: 'ორიგინალური ორკესტრული სკორი — სიმები, სპილენძი, პერკუსია', ru: 'Оригинальная оркестровая партитура — струнные, медь, перкуссия' },
  },
  {
    id: 'text-demo', service: 'Text & Copy', icon: '✍️', accent: '#818cf8',
    prompt: { en: '"Write a product description for a smart home device"', ka: '"დაწერე პროდუქტის აღწერა ჭკვიანი სახლის მოწყობილობისთვის"', ru: '"Напиши описание продукта для устройства умного дома"' },
    outputType: 'text',
    mockOutput: { en: 'Introducing the HaloSphere — the intelligent home companion that learns your rhythm. Seamlessly controls lighting, climate, and security with a single voice command. Designed for modern living.', ka: 'გაცანით HaloSphere — ჭკვიანი სახლის სპუტნიკი, რომელიც სწავლობს თქვენს რიტმს. მართავს განათებას, კლიმატს და უსაფრთხოებას ერთი ხმოვანი ბრძანებით.', ru: 'Представляем HaloSphere — умный домашний спутник, который учится вашему ритму. Управляет светом, климатом и безопасностью одной голосовой командой.' },
  },
]

/* ── Output type visual badge ── */
const TYPE_LABELS: Record<string, { en: string; ka: string; ru: string; icon: string }> = {
  image: { en: 'Image Output', ka: 'სურათის შედეგი', ru: 'Изображение', icon: '🖼️' },
  video: { en: 'Video Output', ka: 'ვიდეო შედეგი', ru: 'Видео', icon: '🎬' },
  audio: { en: 'Audio Output', ka: 'აუდიო შედეგი', ru: 'Аудио', icon: '🎵' },
  text: { en: 'Text Output', ka: 'ტექსტის შედეგი', ru: 'Текст', icon: '✍️' },
}

const DemoCard = memo(function DemoCard({ item, lang: _lang, active, onSelect }: { item: DemoItem; lang: Lang; active: boolean; onSelect: () => void }) {
  return (
    <button
      onClick={onSelect}
      className="shrink-0 flex items-center gap-2.5 px-4 py-2.5 rounded-xl transition-all duration-200 active:scale-[0.97] select-none whitespace-nowrap"
      style={{
        background: active
          ? `linear-gradient(135deg, ${item.accent}22, ${item.accent}0a)`
          : 'linear-gradient(135deg, rgba(255,255,255,0.04), rgba(255,255,255,0.01))',
        border: active ? `1px solid ${item.accent}55` : '1px solid rgba(255,255,255,0.06)',
        boxShadow: active ? `0 0 20px ${item.accent}15` : 'none',
      }}
    >
      <span className="text-base">{item.icon}</span>
      <span className="text-xs font-bold" style={{ color: active ? item.accent : 'rgba(255,255,255,0.7)' }}>
        {item.service}
      </span>
    </button>
  )
})

export function DemoPreviewSection() {
  const { language } = useLanguage()
  const lang = (language as Lang) || 'en'
  const c = COPY[lang] || COPY.en
  const [activeIdx, setActiveIdx] = useState(0)
  const item = DEMOS[activeIdx] ?? DEMOS[0]
  if (!item) return null
  const typeLabel = TYPE_LABELS[item.outputType] ?? TYPE_LABELS.image
  if (!typeLabel) return null

  return (
    <section className="cinematic-section relative px-4 sm:px-6 lg:px-10 py-20 sm:py-28 overflow-hidden">
      <div className="absolute inset-0 pointer-events-none" style={{ background: 'radial-gradient(ellipse 60% 40% at 50% 60%, rgba(34,211,238,0.03) 0%, transparent 70%)' }} />

      <div className="relative max-w-5xl mx-auto">
        {/* Header */}
        <div className="text-center mb-10 sm:mb-14">
          <p className="text-[10px] sm:text-[11px] tracking-[0.3em] uppercase font-black mb-3" style={{ color: '#22d3ee', textShadow: '0 0 20px rgba(34,211,238,0.3)' }}>
            {c.eyebrow}
          </p>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold tracking-tight" style={{ color: 'rgba(255,255,255,0.95)' }}>
            {c.title}
          </h2>
          <p className="mt-4 text-sm sm:text-base max-w-2xl mx-auto" style={{ color: 'rgba(255,255,255,0.45)' }}>
            {c.sub}
          </p>
        </div>

        {/* Service filter tabs */}
        <div className="flex gap-2 overflow-x-auto pb-3 mb-6" style={{ scrollbarWidth: 'none' }}>
          {DEMOS.map((d, i) => (
            <DemoCard key={d.id} item={d} lang={lang} active={activeIdx === i} onSelect={() => setActiveIdx(i)} />
          ))}
        </div>

        {/* Demo card — the visual preview window */}
        <AnimatePresence mode="wait">
          <motion.div
            key={item.id}
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -12 }}
            transition={{ duration: 0.3 }}
          >
            <div
              className="holo-panel relative !rounded-3xl overflow-hidden"
              style={{
                background: 'linear-gradient(170deg, #0b1219, #080e14 40%, #0a1018)',
                boxShadow: `0 8px 60px rgba(0,0,0,0.5), 0 0 60px ${item.accent}08, inset 0 1px 0 rgba(255,255,255,0.04)`,
              }}
            >
              {/* Window chrome */}
              <div
                className="flex items-center justify-between px-4 sm:px-6 py-3"
                style={{
                  background: 'linear-gradient(180deg, rgba(255,255,255,0.04), rgba(255,255,255,0.01))',
                  borderBottom: '1px solid rgba(255,255,255,0.06)',
                }}
              >
                <div className="flex items-center gap-2">
                  <div className="flex gap-1.5">
                    <div className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: 'rgba(255,95,87,0.7)' }} />
                    <div className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: 'rgba(255,189,46,0.7)' }} />
                    <div className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: 'rgba(39,201,63,0.7)' }} />
                  </div>
                  <span className="ml-3 text-[10px] font-bold tracking-[0.15em] uppercase" style={{ color: 'rgba(255,255,255,0.3)' }}>
                    AI OUTPUT PREVIEW
                  </span>
                </div>
                <div className="flex items-center gap-1.5">
                  <span className="text-xs">{typeLabel.icon}</span>
                  <span className="text-[9px] font-bold" style={{ color: `${item.accent}99` }}>
                    {typeLabel[lang]}
                  </span>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 min-h-[320px]">
                {/* LEFT: Prompt input display */}
                <div className="p-5 sm:p-6 flex flex-col justify-center" style={{ borderRight: '1px solid rgba(255,255,255,0.04)' }}>
                  <div className="flex items-center gap-2 mb-4">
                    <div className="w-1.5 h-1.5 rounded-full" style={{ backgroundColor: item.accent, boxShadow: `0 0 6px ${item.accent}` }} />
                    <span className="text-[10px] font-bold tracking-[0.1em] uppercase" style={{ color: 'rgba(255,255,255,0.35)' }}>
                      {lang === 'ka' ? 'პრომპტი' : lang === 'ru' ? 'Промпт' : 'PROMPT'}
                    </span>
                  </div>
                  <div
                    className="rounded-xl px-4 py-3 mb-5"
                    style={{ background: 'rgba(0,0,0,0.3)', border: '1px solid rgba(255,255,255,0.06)' }}
                  >
                    <p className="text-sm italic leading-relaxed" style={{ color: 'rgba(255,255,255,0.6)' }}>
                      {item.prompt[lang]}
                    </p>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className="text-2xl">{item.icon}</span>
                    <div>
                      <div className="text-xs font-bold" style={{ color: item.accent }}>{item.service}</div>
                      <div className="text-[10px]" style={{ color: 'rgba(255,255,255,0.3)' }}>MyAvatar.ge</div>
                    </div>
                  </div>
                </div>

                {/* RIGHT: Output preview */}
                <div className="p-5 sm:p-6 flex flex-col justify-center">
                  <div className="flex items-center gap-2 mb-4">
                    <div className="w-1.5 h-1.5 rounded-full animate-pulse" style={{ backgroundColor: '#34d399', boxShadow: '0 0 6px #34d399' }} />
                    <span className="text-[10px] font-bold tracking-[0.1em] uppercase" style={{ color: 'rgba(255,255,255,0.35)' }}>
                      {lang === 'ka' ? 'შედეგი' : lang === 'ru' ? 'Результат' : 'OUTPUT'}
                    </span>
                  </div>

                  {/* Visual output mock */}
                  <div
                    className="rounded-xl overflow-hidden mb-4"
                    style={{
                      background: `linear-gradient(135deg, ${item.accent}10, ${item.accent}05)`,
                      border: `1px solid ${item.accent}20`,
                      minHeight: '140px',
                    }}
                  >
                    {item.outputType === 'text' ? (
                      <div className="p-4">
                        <p className="text-sm leading-relaxed" style={{ color: 'rgba(255,255,255,0.75)' }}>
                          {item.mockOutput[lang]}
                        </p>
                      </div>
                    ) : (
                      <div className="relative h-[160px] flex items-center justify-center">
                        {/* Mock visual placeholder with service color gradient */}
                        <div
                          className="absolute inset-0"
                          style={{ background: `linear-gradient(135deg, ${item.accent}15, rgba(0,0,0,0.3) 60%, ${item.accent}08)` }}
                        />
                        <div className="relative text-center z-10">
                          <div className="text-4xl mb-2">{typeLabel.icon}</div>
                          <p className="text-[10px] max-w-[200px] mx-auto leading-relaxed" style={{ color: 'rgba(255,255,255,0.4)' }}>
                            {item.mockOutput[lang]}
                          </p>
                        </div>
                      </div>
                    )}
                  </div>

                  {/* Action buttons */}
                  <div className="flex gap-2">
                    <button className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[10px] font-bold transition-all active:scale-95"
                      style={{ background: `${item.accent}18`, border: `1px solid ${item.accent}30`, color: item.accent }}>
                      <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
                      {lang === 'ka' ? 'ჩამოტვირთვა' : lang === 'ru' ? 'Скачать' : 'Download'}
                    </button>
                    <button className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[10px] font-bold transition-all active:scale-95"
                      style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)', color: 'rgba(255,255,255,0.5)' }}>
                      <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z"/></svg>
                      {lang === 'ka' ? 'რედაქტირება' : lang === 'ru' ? 'Редактировать' : 'Edit'}
                    </button>
                    <button className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[10px] font-bold transition-all active:scale-95"
                      style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)', color: 'rgba(255,255,255,0.5)' }}>
                      <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><polyline points="15 3 21 3 21 9"/><path d="M10 14L21 3"/><path d="M18 13v6a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h6"/></svg>
                      {lang === 'ka' ? 'სერვისში' : lang === 'ru' ? 'В сервис' : 'Send to Service'}
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </motion.div>
        </AnimatePresence>
      </div>
    </section>
  )
}
