// GENERATED by scripts/templates/build-thumb-blur.mjs — do not edit by hand. Re-run it whenever a template thumbnail
// is added or replaced (`node scripts/templates/build-thumb-blur.mjs`; build-thumbs.mjs runs it after every build).
// `v` = the first 10 hex of the file's SHA-256 (the gallery requests `<path>?v=<v>`); `blur` = a ≤ 16 px WebP of it
// for next/image's placeholder="blur". lib/studio/templateThumbs.test.ts fails when an entry is stale or missing.
export const TEMPLATE_THUMB_META: Readonly<Record<string, { readonly v: string; readonly blur: string }>> = {
  '/avatars/preset-1.jpg': { v: '0b6a6bdb35', blur: 'data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAAAwAgCdASoQABAAAoBCJQBOgCBTHDTbHlNOAAD+6peV+DRmW37E60HcOteTFCC8xiTP3FE2z6rn/AhtcjG7Te+U5VDU+Boqs4Cd1rdLKJTC2EML1vLxEbJBTUbvea2WsmBU1n44YkVX49Gs2p3knh1Z/C3ltjaCyEGevOyWMk7oQ0jgAAA=' },
  '/avatars/preset-2.jpg': { v: '93c7816fbb', blur: 'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABwAgCdASoQABAAAoBCJYwCdH8AGEa9Iaq37ZyAAP6pl1zjNGackub461tT07f2vXNiu6RFgqgTu1Oj9OX+YsVCKMXbd5SXKEO+zkJQ5FWMf+0BsW1cugL5bAAUTxey92QlwLTJqEsB8BYDycAAAA==' },
  '/avatars/preset-3.jpg': { v: 'bbc8ce5a1c', blur: 'data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABQAgCdASoQABAAAoBCJQBOgMXr1Q/Me5pZNQAA/j9OAfERd3XuYEeIb+wCxHcTEcC214UzmbT0yOL+C8eTWpUcgZMjrTfJ8U80nqVx7ZN357nk6+fB91LZJaDRxMkcuwXN2JiekAA=' },
  '/avatars/preset-4.jpg': { v: '0413a0ed22', blur: 'data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAwAgCdASoQABAAAoBCJYwCdAYulPfUnqF04AD+38EWT114lIWL5fD2ul9DiKzMBa7nG5zSBM34LfhLO3CH6xksl1ECSRbfruPmKashzL32ghs04nJLXhPlrfn64g2a8Q1XIJTZ9aZmwD33NjtIdmvsnBBxQosAAAA=' },
  '/avatars/preset-5.jpg': { v: 'be6013913e', blur: 'data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABQAgCdASoQABAAAoBCJQBOgMVV1Qk/GPyYxOAA9gAL32B5enp4ICkPNYB6DPI6vyN/9xHgBMfVd515sELu687VSnE/HRabP+nb+zuvfhSY+cZNg47EsPcrXUrTrSDV6Rd23bbfIqAAAA==' },
  '/avatars/preset-6.jpg': { v: '078b2b318a', blur: 'data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABQAgCdASoQABAAAoBCJZQCdAYsjRvDavs2EQAA/YqlxkhHL3pyo51m1uWbSuhQpOF53OEUyKO3Br5+Y0Yu4/CtUA4UHm3MnAj8RSpma4BVQbe6JJV/FTbhUevT4n7rElNgAA==' },
  '/templates/image/product.jpg': { v: 'f10b79bc5d', blur: 'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoMABAAAoBCJQBWACFsF1uIwMEAAP78R287OcyOOry2+seEGbqLqcfMVE0GFURf9m7CCmN/11V6zKw03Pj++qNt5tegAA==' },
  '/templates/music/lofi-chill.jpg': { v: '9b2c091f6e', blur: 'data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoMABAAAoBCJQBOj+ADARqqQAD++Si6UC7BiAyXhlknzPXXAYkF3NGYU1opdfbQr5KMYz7KEQRfBRYy+4+wyhucrMuMSB5k5ZwEGz3C8oAAAA==' },
  '/templates/video/reel.jpg': { v: 'cbd96700f4', blur: 'data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoMABAAAoBCJYwCdADWyIB0AAD++ffqQRSl7QnEZ4CsyVTe0lNOJcUT4aa3vtwPm03Ya3CccZZaLy3KHz0Qhp7QAAA=' },
  '/templates/video/trailer.jpg': { v: '399a2a708c', blur: 'data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAABQAQCdASoMABAAAoBCJQBOgCgAAP7zrmnx88v+lat9TEvzKar4kxBhjGuLi9rkQAA=' },
};
