import { getEnv } from '@/lib/env/schema';

export type PublicEnv = {
  NEXT_PUBLIC_SUPABASE_URL?: string;
  NEXT_PUBLIC_SUPABASE_ANON_KEY?: string;
  NEXT_PUBLIC_BACKEND_URL?: string;
  NEXT_PUBLIC_SITE_URL?: string;
  NEXT_PUBLIC_BASE_URL?: string;
  NEXT_PUBLIC_AUTH_REDIRECT_URL?: string;
  NEXT_PUBLIC_SUPABASE_PHONE_AUTH_ENABLED?: string;
  NEXT_PUBLIC_APP_URL?: string;
  NEXT_PUBLIC_FRONTEND_ORIGIN?: string;
  NEXT_PUBLIC_PENTAGON_API_URL?: string;
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY?: string;
  NEXT_PUBLIC_MOCK_MODE?: string;
};

const requiredPublicKeys: Array<keyof PublicEnv> = [
  'NEXT_PUBLIC_SUPABASE_URL',
  'NEXT_PUBLIC_SUPABASE_ANON_KEY',
];

export const publicEnv: PublicEnv = {
  NEXT_PUBLIC_SUPABASE_URL: getEnv().NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: getEnv().NEXT_PUBLIC_SUPABASE_ANON_KEY,
  NEXT_PUBLIC_BACKEND_URL: getEnv().NEXT_PUBLIC_BACKEND_URL,
  NEXT_PUBLIC_SITE_URL: getEnv().NEXT_PUBLIC_SITE_URL,
  NEXT_PUBLIC_BASE_URL: getEnv().NEXT_PUBLIC_BASE_URL,
  NEXT_PUBLIC_AUTH_REDIRECT_URL: getEnv().NEXT_PUBLIC_AUTH_REDIRECT_URL,
  NEXT_PUBLIC_SUPABASE_PHONE_AUTH_ENABLED: getEnv().NEXT_PUBLIC_SUPABASE_PHONE_AUTH_ENABLED,
  NEXT_PUBLIC_APP_URL: getEnv().NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_FRONTEND_ORIGIN: getEnv().NEXT_PUBLIC_FRONTEND_ORIGIN,
  NEXT_PUBLIC_PENTAGON_API_URL: getEnv().NEXT_PUBLIC_PENTAGON_API_URL,
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: getEnv().NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
  NEXT_PUBLIC_MOCK_MODE: getEnv().NEXT_PUBLIC_MOCK_MODE,
};

if (typeof window !== 'undefined') {
  const missing = requiredPublicKeys.filter((key) => !publicEnv[key]);
  if (missing.length > 0) {
    console.warn(
      `[env] missing required public env vars: ${missing.join(', ')}`
    );
  }
}
